// Doom-loop detection (FR-007 / SC-012).
// Watches text generated by the model during reasoning/task-generation. If the same
// phrase repeats more than a configurable threshold of consecutive times, it's flagged
// as a doom loop; the caller reformulates the instruction and re-sends it.

export interface DoomLoopResult {
  detected: boolean;
  repeatedPhrase?: string;
  repetitions: number;
}

const MAX_PHRASE_LEN = 400; // cap so single tokens / huge repeats can't be counted trivially

/**
 * Detect consecutive identical phrases in generated text. A "phrase" is a tokenized,
 * whitespace-normalized chunk of the model output. SC-012 default threshold = 4.
 */
export function detectDoomLoop(text: string | null, threshold = 4): DoomLoopResult {
  if (!text || typeof text !== 'string') return { detected: false, repetitions: 0 };

  const tokens = tokenize(text);
  // Find the longest run of an identical token sequence that meets/exceeds the threshold.
  let bestRun = '';
  let bestCount = 0;

  for (let i = 0; i < tokens.length - threshold + 1; i++) {
    const candidate = tokens.slice(i, i + threshold).join(' ');
    if (!candidate || candidate.length > MAX_PHRASE_LEN) continue;
    // count how many times this exact run repeats consecutively
    let count = 1;
    for (let j = i + threshold; ; ) {
      const next = tokens.slice(j, j + threshold).join(' ');
      if (next === candidate) {
        count += 1;
        j += threshold;
      } else {
        break;
      }
    }
    if (count >= threshold && count > bestCount && candidate.length >= 8) {
      bestCount = count;
      bestRun = candidate;
    }
  }

  const longTokenRun = runOfSingleLongToken(tokens);
  return {
    detected: bestCount >= threshold || longTokenRun >= threshold,
    repeatedPhrase: bestRun || undefined,
    repetitions: Math.max(bestCount, longTokenRun),
  };
}

/** Count a single long token repeated consecutively above threshold. */
function runOfSingleLongToken(tokens: string[]): number {
  let max = 0;
  let run = 1;
  for (let i = 1; i < tokens.length; i++) {
    if (tokens[i] === tokens[i - 1]) {
      run += 1;
      if (run > max) max = run;
    } else {
      run = 1;
    }
  }
  return max >= 4 ? max : 0;
}

function tokenize(text: string): string[] {
  // Lowercase, strip everything but alphanumerics + spaces, split on whitespace.
  const clean = text.toLowerCase().replace(/[^a-z0-9\s]/g, ' ');
  return clean.split(/\s+/).filter(Boolean);
}
