// File-backed structured logger with automatic per-file rotation (~10 MB/file).
// SC-025: timestamps, session ids, trace ids, severity levels; auto-rotate at 10 MB.
//
// Tracing model: every incoming HTTP request owns a `trace_id` (client-supplied via the
// `x-trace-id` header or generated by the proxy). Every log line emitted while handling that
// request carries it, so one `grep <trace_id>` reconstructs the whole operation end-to-end
// (route -> model resolution -> agent loop phases -> upstream provider calls -> stream end).

import { mkdirSync, appendFileSync, statSync, existsSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import env from './config.js';

type Level = 'debug' | 'info' | 'warn' | 'error';

interface Line {
  ts: string;
  level: Level;
  sid?: string;
  trace?: string;
  msg: string;
}

// ---- ANSI colors (console mirror only — the log FILE always receives plain text) ----

const ANSI = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  magenta: '\x1b[35m',
  dim: '\x1b[2m',
} as const;

/**
 * Colors are emitted when a terminal is attached OR when the caller opts in explicitly
 * (FORCE_COLOR=1, e.g. for `nohup … > proxy-dev.log 2>&1` tails). NO_COLOR disables them.
 */
function colorEnabled(): boolean {
  if (process.env.NO_COLOR) return false;
  if (process.env.FORCE_COLOR) return true;
  return !!(process.stdout.isTTY || process.stderr.isTTY);
}

/** Wrap `text` in an ANSI color (no-op when colors are disabled). */
export function paint(text: string, color: keyof typeof ANSI): string {
  if (!colorEnabled()) return text;
  return `${ANSI[color]}${text}${ANSI.reset}`;
}

/** An HTTP status code rendered in its result color: 2xx/3xx green, 408/429 yellow, 4xx/5xx red. */
export function statusColor(code: number): string {
  const color: keyof typeof ANSI = code < 400 ? 'green' : code === 408 || code === 429 ? 'yellow' : 'red';
  return paint(`${code}`, color);
}

const MAX_BYTES_PER_FILE = 10 * 1024 * 1024; // rotate after this many bytes/file
let currentSeq = seqFromNow();

function seqFromNow(): number {
  const d = new Date();
  return Number(d.toISOString().slice(0, 10).replace(/-/g, '')); // YYYYMMDD
}

function currentFile(): string {
  return `${env.LOG_DIR}/evolve-proxy-${currentSeq}.log`;
}

// Append-per-line (no in-process buffer): an audit trail that is only visible after 1024 lines
// is not an audit trail. The volume here is request-rate, so a sync append per line is cheap
// and guarantees every operation is durably on disk the moment it happens. Rotation is
// checked after each append (rotates to the next sequence number past 10 MB).
function rotateIfNeeded(): void {
  try {
    if (existsSync(currentFile()) && statSync(currentFile()).size > MAX_BYTES_PER_FILE) {
      currentSeq += 1;
    }
  } catch {
    /* ignore */
  }
}

/** Console color for a severity tag: error red, warn yellow, debug dim, info green. */
function levelTagColor(level: Level): keyof typeof ANSI {
  switch (level) {
    case 'error': return 'red';
    case 'warn': return 'yellow';
    case 'debug': return 'dim';
    default: return 'green'; // info
  }
}

/**
 * Render the `<time> [<LEVEL>] <sid> <trace> ` prefix. The LOG FILE always receives the
 * plain variant; the CONSOLE mirror gets the severity tag colored so a long stream is
 * scannable at a glance (colors are console-only and respect NO_COLOR/FORCE_COLOR).
 */
function linePrefix(l: Line, colored: boolean): string {
  const tag = colored ? paint(`[${l.level.toUpperCase()}]`, levelTagColor(l.level)) : `[${l.level.toUpperCase()}]`;
  return `${l.ts} ${tag} ${l.sid ?? '-'} ${l.trace ?? '-'} `;
}

/**
 * A logger bound to a session and (optionally) a request trace id. `traced(id)` returns a
 * copy bound to one `trace_id`; the level methods of the bound copy keep the session and add
 * the trace to every line. This is the type every layer (routes, agent loop, providers)
 * receives so one `grep <trace_id>` over the log file reconstructs a full request lifecycle.
 */
export interface TraceLogger {
  debug(msg: string, consoleLine?: string): void;
  info(msg: string, consoleLine?: string): void;
  warn(msg: string, consoleLine?: string): void;
  error(msg: string, consoleLine?: string): void;
  /** Return a copy of this logger bound to the given trace id. */
  traced(traceId: string): TraceLogger;
  /**
   * INFO request-result line: the LOG FILE receives the plain `fileMsg`; the CONSOLE mirror
   * receives `consoleLine`, which may carry ANSI colors (e.g. a colorized HTTP status).
   */
  requestResult(fileMsg: string, consoleLine: string): void;
}

/** Build a logger bound to one session id (SC-025 per-request audit trail). */
export function createLogger(sessionId: string): TraceLogger {
  return makeLogger(sessionId, undefined);
}

function makeLogger(sid: string, traceId: string | undefined): TraceLogger {
  return {
    debug(msg: string, consoleLine?: string): void { log('debug', sid, traceId, msg, consoleLine); },
    info(msg: string, consoleLine?: string): void { log('info', sid, traceId, msg, consoleLine); },
    warn(msg: string, consoleLine?: string): void { log('warn', sid, traceId, msg, consoleLine); },
    error(msg: string, consoleLine?: string): void { log('error', sid, traceId, msg, consoleLine); },
    traced(id: string): TraceLogger { return makeLogger(sid, id); },
    requestResult(fileMsg: string, consoleLine: string): void {
      log('info', sid, traceId, fileMsg, consoleLine);
    },
  };
}

/** Mint a compact, sortable trace id for requests that arrive without an `x-trace-id` header. */
export function newTraceId(): string {
  return `tr_${Date.now().toString(36)}_${randomUUID().replace(/-/g, '').slice(0, 8)}`;
}

function log(
  level: Level,
  sid: string | undefined,
  traceId: string | undefined,
  msg: string,
  /** Optional pre-rendered console body (ANSI colors allowed). The file always gets the plain line. */
  consoleLine?: string,
): void {
  const l: Line = { ts: new Date().toISOString(), level, sid, trace: traceId, msg };
  // The log FILE always receives the plain line (no ANSI, ever).
  const fileLine = linePrefix(l, false) + msg;
  if (env.CONSOLE_LOG) {
    // Live visibility: mirror every line to the console (errors/warnings to stderr, the rest
    // to stdout) with a colorized severity tag so incoming connections and their trace ids
    // are visible without tailing the file. When a dedicated console rendering is given
    // (e.g. colorized status/method), it replaces the plain body ONLY on the console.
    try {
      const consoleOut = linePrefix(l, true) + (consoleLine ?? msg);
      (level === 'error' || level === 'warn' ? process.stderr : process.stdout).write(consoleOut + '\n');
    } catch {
      /* console is best-effort */
    }
  }
  try {
    mkdirSync(env.LOG_DIR, { recursive: true });
    appendFileSync(currentFile(), fileLine + '\n');
    rotateIfNeeded();
  } catch {
    /* logging must never crash a request */
  }
}
